openapi: 3.0.0
info:
  title: ALIR Web Api
  description: 'Documentazione Api'
  contact:
    name: API Support
    email: andreacw5@live.com
  version: '1.0'
servers:
- url: http://localhost:3000
  description: Server locale
- url: https://api.alir.eu
  description: Server remoto
paths:
  '/list':
    get:
      tags:
      - General
      parameters:
      - name: side
        in: query
        schema:
          type: string
          enum: ["cop", "med"]
        description: codice fazione
      summary: Elenco dei giocatori  della fazione
      description: Restitisce l'elenco dei giocatori della fazione
      operationId: factionList
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Players'
        404:
          description: "Not found"
        401:
          $ref: '#/components/responses/UnauthorizedError'
  '/players':
    get:
      tags:
      - Players
      summary: Elenco dei giocatori
      description: Restitisce l'elenco dei giocatori
      operationId: playerList
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Players'
        404:
          description: "Not found"
        401:
          $ref: '#/components/responses/UnauthorizedError'
  '/players/{playerId}':
    get:
      tags:
      - Players
      summary: Elenco dei giocatori trovati
      parameters:
      - name: playerId
        in: path
        schema:
          type: string
        description: playerId del giocatore o nome del giocatore
      description: Restitisce l'elenco dei giocatori trovati, può ritornare uno o più player in base al tipo di ricerca
      operationId: playerSearch
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Players'
        404:
          description: "Not found"
        401:
          $ref: '#/components/responses/UnauthorizedError'
  '/vehicles/{playerId}':
    get:
      tags:
      - Vehicles
      summary: Elenco dei veicoli di un giocatore
      parameters:
      - name: playerId
        in: path
        schema:
          type: string
        description: playerId del giocatore o nome del giocatore
      description: Elenco dei veicoli di un giocatore
      operationId: vehicleList
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicles'
        404:
          description: "Not found"
        401:
          $ref: '#/components/responses/UnauthorizedError'
  '/gangs':
    get:
      tags:
      - Gangs
      summary: Elenco delle gang
      description: Restitisce l'elenco delle gang
      operationId: gangList
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Gangs'
        404:
          description: "Not found"
        401:
          $ref: '#/components/responses/UnauthorizedError'
  '/gangs/{gangId}':
    get:
      tags:
      - Gangs
      summary: Dettagli di una gang
      description: Restitisce li dettagli di una gang
      operationId: gangShow
      parameters:
      - name: gangId
        in: path
        schema:
          type: string
        description: Id della gang
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Gang'
        404:
          description: "Not found"
        401:
          $ref: '#/components/responses/UnauthorizedError'
components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
  schemas:
    Gangs:
      type: object
      properties:
        pid:
          type: integer
          description: Identificativo univoco del giocatore steam
    Gang:
      type: object
      properties:
        pid:
          type: integer
          description: Identificativo univoco del giocatore steam
    Vehicles:
      type: object
      properties:
        pid:
          type: integer
          description: Identificativo univoco del giocatore steam
        classname:
          type: string
          description: Nome del veicolo
        alive:
          type: integer
          description: Indica se il veicolo è attivo sul server
        type:
          type: string
          enum: ["Car", "Air", "Boat"]
          description: Tipologia del mezzo
        side:
          type: string
          enum: ["civ", "cop", "med"]
          description: Fazione del veicolo
        color:
          type: integer
          description: Colore del veicolo
        plate:
          type: integer
          description: Targa del veicolo
      example:
        pid: 234235436564
        plate: 324
        classname: "O_Truck_03_transport_F"
        type: "Car"
        side: "civ"
        alive: 1
        color: 0
    Players:
      type: object
      properties:
        uid:
          type: integer
          description: Identificativo univoco del giocatore sul database
        playerid:
          type: integer
          maxLength: 17
          description: Codice univoco del giocatore di steam
        cash:
          type: integer
          description: Contanti dell'utente
        bankacc:
          type: integer
          description: Denaro sul conto corrente dell'utente
        name:
          type: string
          description: Nome dell'utente sul server
        aliases:
          type: string
          description: Nomi dell'utente precedenti
        coplevel:
          type: integer
          maximum: 11
          description: Livello polizia del giocatore
        mediclevel:
          type: integer
          maximum: 8
          description: Livello medico del giocatore
        adaclevel:
          type: integer
          maximum: 5
          description: Livello meccanico del giocatore
          deprecated: true
        adminlevel:
          type: integer
          maximum: 5
          description: Livello amministratore del giocatore
        insert_time:
          type: string
          format: date-time
          description: Data di inserimento sul db
        civ_licenses:
          type: array
          description: Licenze possedute
      example:
        uid: 1
        playerid: 76561198036665850
        cash: 245
        bankacc: 23489
        name: Bowen
        aliases: Merez
        coplevel: 3
        mediclevel: 0
        adaclevel: 0
        adminlevel: 5
        insert_time: 2018-11-01T17:46:33
        civ_licenses: []
tags:
  - name: Players
    description: Api relative ai giocatori
  - name: Vehicles
    description: Api relative ai veicoli
  - name: Gangs
    description: Api relative alle gang
  - name: Users
    description: Api relative agli utenti del forum
  - name: General
    description: Api generiche
  - name: Wanted
    description: Api relative alla lista ricercati
